[project]
name = "mlopspython-inference"
version = "0.0.0"
description = ""
readme = "README.md"
authors = [{ name = "Guillaume Chervet", email = "guillaume.chervet@gmail.com" }]
requires-python = ">=3.8,<3.11"
dependencies = [
  "opencv-contrib-python-headless==4.8.0.76",
  "keras==2.12.0",
  "tensorflow==2.12.0",
  "tensorflow-io-gcs-filesystem==0.27.0",
  "pillow==10.0.1",
]

[tool.hatch.build.targets.wheel]
packages = ["mlopspython_inference"]

[dependency-groups]
dev = ["coverage>=7.3.1,<8"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
