[project]
name = "mlopspython-inference"
version = "0.0.0"
description = ""
readme = "README.md"
authors = [{ name = "Guillaume Chervet", email = "guillaume.chervet@gmail.com" }]
requires-python = ">=3.11,<3.12"
dependencies = [
 "opencv-contrib-python-headless==4.8.0.76",
    "tensorflow==2.20.*",
  "keras==3.*",
     "numpy>=1.26,<2",
  "pillow>=10,<11",
      # Installe seulement hors Windows (utile pour gs:// sur Linux/macOS)
  "tensorflow-io-gcs-filesystem; platform_system != 'Windows'",
]

[tool.hatch.build.targets.wheel]
packages = ["mlopspython_inference"]

[dependency-groups]
dev = [
  "pytest>=8.0",
  "pytest-cov>=5.0",
]
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.uv]
required-environments = [
  "platform_system == 'Windows' and python_version >= '3.11'",
  "platform_system == 'Linux' and python_version >= '3.11'",
  "platform_system == 'Darwin' and python_version >= '3.11'",
]